export const NIGERIAN_BANKS: string[] = [
  'Access Bank',
  'Access Bank (Diamond)',
  'ALAT by Wema',
  'ASO Savings and Loans',
  'Atlas Bank',
  'Carbon',
  'CEMCS Microfinance Bank',
  'Citibank Nigeria',
  'Coronation Merchant Bank',
  'Cosmopolitan MFB',
  'Ecobank Nigeria',
  'Ekondo MFB',
  'Fidelity Bank',
  'First Bank of Nigeria',
  'First City Monument Bank (FCMB)',
  'FSDH Merchant Bank',
  'Globus Bank',
  'Guaranty Trust Bank (GTBank)',
  'Halifax Bank',
  'Heritage Bank',
  'Infinity MFB',
  'Jaiz Bank',
  'Keystone Bank',
  'Kuda Microfinance Bank',
  'Lagos Building Investment Company',
  'Mayfair MFB',
  'Money Trust MFB',
  'Nagarta Microfinance Bank',
  'Nigeria Navy Microfinance Bank',
  'NPF Microfinance Bank',
  'One Finance',
  'Opay',
  'Paga',
  'PalmPay',
  'Parallex Bank',
  'Parkway - ReadyCash',
  'Paycom (OPay)',
  'Pazuri MFB',
  'Polaris Bank',
  'Premium Trust Bank',
  'Providus Bank',
  'Rand Merchant Bank',
  'Rubies MFB',
  'Signature Bank',
  'Sparkasse MFB',
  'Stanbic IBTC Bank',
  'Standard Chartered Bank',
  'Sterling Bank',
  'Suntrust Bank',
  'TAJ Bank',
  'TCF MFB',
  'Titan Bank',
  'Union Bank of Nigeria',
  'United Bank for Africa (UBA)',
  'Unity Bank',
  'VFD Microfinance Bank',
  'Wema Bank',
  'Zenith Bank',
];
